* Create /dev/open-mx in omx_init in case udev was not running. * Set group to root and mode to 666 by default so that anybody   may use Open-MX. * Add --with-device configure option to change the device name,   group or mode.
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/open-mx/trunk@574 f1ba3bf5-cb5c-402b-92a9-7c6bdc83a356

diff --git a/tools/omx_init.in b/tools/omx_init.in
--- a/tools/omx_init.in
+++ b/tools/omx_init.in
@@ -14,6 +14,9 @@
 
 # Note that this is replaced by make install, not configure!
 OMX_PREFIX=@omx_install_prefix@
+DEVICE=@omx_device_name@
+GROUP=@omx_device_group@
+MODE=@omx_device_mode@
 
 LINUX_RELEASE=$(uname -r)
 
@@ -31,6 +34,7 @@ unload_omx() {
         echo "Removing Open-MX driver"
         /sbin/rmmod open-mx
     fi
+    rm -f "$DEVICE"
 }
 
 # Load the Open-MX module
@@ -39,6 +43,23 @@ load_omx() {
     params=" $OMX_MODULE_PARAMS $*"
 
     /sbin/insmod ${OMX_PREFIX}/lib/modules/${LINUX_RELEASE}/open-mx.ko $params
+
+    if ! test -e $DEVICE; then
+	echo "Creating '$DEVICE'"
+	major=$(sed -nr -e '/^Character devices:/,/^Block devices:/s/ *([0-9]+) *misc/\1/p' /proc/devices)
+	minor=$(sed -nr -e 's/ *([0-9]+) *open-mx/\1/p' /proc/misc)
+	if test -z "$major" -o -z "$minor"; then
+	    echo "[ERROR] Failed to retrieve device major/minor numbers"
+	else
+	    mknod "$DEVICE" c "$major" "$minor" \
+		|| echo "[ERROR] Failed to create device node"
+	fi
+    fi
+    echo "Setting group '$GROUP' and mode '$MODE' or device '$DEVICE'"
+    chgrp "$GROUP" "$DEVICE" \
+	|| echo "[ERROR] Failed to set mode"
+    chmod "$MODE" "$DEVICE" \
+	|| echo "[ERROR] Failed to set group"
 }
 
 cmd="$1"
