tests: add omx_truncated_test to check that xfer_length/msg_length and the recv buffer are properly updated when the receive buffer is too small
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/open-mx/trunk@2741 f1ba3bf5-cb5c-402b-92a9-7c6bdc83a356

diff --git a/tools/omx_check.sh.in b/tools/omx_check.sh.in
--- a/tools/omx_check.sh.in
+++ b/tools/omx_check.sh.in
@@ -200,6 +200,15 @@ if [ $domisc -eq 1 ] ; then
 	fi
 
 	echo
+	echo "**************"
+	echo "TEST truncated"
+	echo "**************"
+	${TESTS_DIR}/omx_truncated_test
+	if [ $? -ne 0 ] ; then
+	    echo "Failed" && exit 1
+	fi
+
+	echo
 	echo "*************"
 	echo "TEST wait_any"
 	echo "*************"
