Bring back 1.2 commit r2877 in the automak'ified build system:   Support DESTDIR in omx_local_install too
Implemented slightly differently (add DESTDIR explicitly in the
low-level command lines instead of only in some variables).

By the way, add a message when DESTDIR is given.

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/open-mx/trunk@2981 f1ba3bf5-cb5c-402b-92a9-7c6bdc83a356

diff --git a/tools/omx_local_install.in b/tools/omx_local_install.in
--- a/tools/omx_local_install.in
+++ b/tools/omx_local_install.in
@@ -18,7 +18,11 @@ UDEV_RULES_DEST=${UDEV_RULES_DIR}/10-open-mx.rules
 
 set -e
 
-if test ! -d ${OMX_PREFIX}; then
+if test x"${DESTDIR}" != x; then
+    echo "Using ${DESTDIR} as the file-system root"
+fi
+
+if test ! -d ${DESTDIR}${OMX_PREFIX}; then
     echo "Something bad happened with the install script"
     echo "OMX_PREFIX isn't pointing to a valid directory"
     exit 1
@@ -31,20 +35,20 @@ cmp_mv_old_and_install_new() {
     dest="$1"; shift
     installname="$1" ; shift
 
-    if test -f "$dest" ; then
+    if test -f "${DESTDIR}$dest" ; then
 	# if no difference, do nothing
-	if cmp -s "$dest" "$src" ; then
+	if cmp -s "${DESTDIR}$dest" "${DESTDIR}$src" ; then
 	    echo "  File $dest is unchanged"
 	    return
 	fi
 
 	# move the old file away
 	echo "  Saving the old $dest into ${dest}.${DATE}..."
-	mv -f "$dest" "${dest}.${DATE}"
+	mv -f "${DESTDIR}$dest" "${DESTDIR}${dest}.${DATE}"
     fi
 
     echo "  Installing $installname $dest..."
-    cp -f "$src" "$dest"
+    cp -f "${DESTDIR}$src" "${DESTDIR}$dest"
 }
 
 cmp_mv_old_and_remove() {
@@ -52,21 +56,21 @@ cmp_mv_old_and_remove() {
     dest="$1"; shift
     installname="$1" ; shift
 
-    if test ! -f "$dest" ; then
+    if test ! -f "${DESTDIR}$dest" ; then
 	echo "  File $dest not found"
 	return
     fi
 
     # if no difference, just remove
-    if cmp -s "$dest" "$src" ; then
+    if cmp -s "${DESTDIR}$dest" "${DESTDIR}$src" ; then
 	echo "  File $dest is unchanged, removing..."
-	rm -f "$dest"
+	rm -f "${DESTDIR}$dest"
 	return
     fi
 
     # move the old file away
     echo "  Saving the old $dest into ${dest}.${DATE}..."
-    mv -f "$dest" "${dest}.${DATE}"
+    mv -f "${DESTDIR}$dest" "${DESTDIR}${dest}.${DATE}"
 }
 
 if test x"$1" != "x--uninstall"; then
@@ -76,18 +80,18 @@ if test x"$1" != "x--uninstall"; then
     cmp_mv_old_and_install_new "${OMX_INIT_SCRIPT}" "${OMX_INIT_SCRIPT_DEST}" "startup script"
 
     echo "Installing config file..."
-    if test ! -d ${OMX_WIDE_CONFIG_DIR} ; then
+    if test ! -d ${DESTDIR}${OMX_WIDE_CONFIG_DIR} ; then
 	echo "  Creating ${OMX_WIDE_CONFIG_DIR} directory..."
-	mkdir ${OMX_WIDE_CONFIG_DIR}
+	mkdir ${DESTDIR}${OMX_WIDE_CONFIG_DIR}
     fi
     cmp_mv_old_and_install_new "${OMX_CONFIG_STUB}" "${OMX_CONFIG_DEST}" "stub config"
 
     if test x$UDEV = x1; then
 	echo "Installing udev rules file..."
-	if test -d ${UDEV_RULES_DIR} ; then
+	if test -d ${DESTDIR}${UDEV_RULES_DIR} ; then
 	    cmp_mv_old_and_install_new "${UDEV_RULES_FILE}" "${UDEV_RULES_DEST}" "udev rules"
 	else
-	    echo "  udev rules directory not found (UDEV_RULES_DIR=$UDEV_RULES_DIR)."
+	    echo "  Udev rules directory not found (UDEV_RULES_DIR=$UDEV_RULES_DIR)."
 	fi
     else
 	echo "Udev support disabled, not installing rules file."
@@ -101,7 +105,7 @@ else
 
     echo "Uninstalling config file..."
     cmp_mv_old_and_remove "${OMX_CONFIG_STUB}" "${OMX_CONFIG_DEST}" "config"
-    test -d "${OMX_WIDE_CONFIG_DIR}" && ( rmdir "${OMX_WIDE_CONFIG_DIR}" 2> /dev/null || echo "  ${OMX_WIDE_CONFIG_DIR} not empty, not removing" )
+    test -d "${DESTDIR}${OMX_WIDE_CONFIG_DIR}" && ( rmdir "${DESTDIR}${OMX_WIDE_CONFIG_DIR}" 2> /dev/null || echo "  ${OMX_WIDE_CONFIG_DIR} not empty, not removing" )
 
     if test x$UDEV = x1; then
 	echo "Uninstalling udev rules file..."
